apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "spring-ai"
spec:
  title: "Spring AI Introduction"
  description: "Discover the power of Spring AI and learn how to integrate AI-driven capabilities into your Spring applications, from leveraging LLMs to building intelligent services with ease."
  publish:
    image: "$(image_repository)/spring-ai-files:$(workshop_version)"
  workshop:
    image: jdk21-environment:*
    files:
    - git:
        url: https://github.com/nevenc/spring-ai-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: xxx-large
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: llama
      spec:
        selector:
          matchLabels:
            app: llama
        template:
          metadata:
            labels:
              app: llama
          spec:
            containers:
              - name: ollama
                image: ollama/ollama
                args:
                - serve
                command:
                - ollama
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - /bin/sh
                        - '-c'
                        - >
                          ollama run llama3.1
                ports:
                - containerPort: 11434
                resources:
                  limits:
                    cpu: 6000m
                    memory: 12Gi
    - apiVersion: v1
      kind: Service
      metadata:
        name: llama
      spec:
        type: ClusterIP
        ports:
          - port: 11434
            targetPort: 11434
        selector:
          app: llama
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vector-store
      spec:
        selector:
          matchLabels:
            app: vector-store
        template:
          metadata:
            labels:
              app: vector-store
          spec:
            containers:
              -   image: redis/redis-stack-server
                  name: workload
    - apiVersion: v1
      kind: Service
      metadata:
        name: vector-store
      spec:
        type: ClusterIP
        selector:
          app: vector-store
        ports:
          - port: 6379
            targetPort: 6379