apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "spring-ai"
spec:
  title: "Spring AI Introduction"
  description: "Discover the power of Spring AI and learn how to integrate AI-driven capabilities into your Spring applications, from leveraging LLMs to building intelligent services with ease."
  publish:
    image: "$(image_repository)/spring-ai-files:$(workshop_version)"
  workshop:
    image: jdk21-environment:*
    files:
    - git:
        #url: https://github.com/nevenc/spring-ai-workshop
        url: https://github.com/timosalm/spring-ai-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: large
      security:
        token:
          enabled: false
        policy: baseline
    resources:
      memory: 4Gi
    ingresses:
    - name: llama
      protocol: http
      host: llama.$(session_namespace)
      port: 11434
      authentication:
        type: none
    - name: deepseek-r1
      protocol: http
      host: deepseek-r1.$(session_namespace)
      port: 11434
      authentication:
        type: none
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: llama
      spec:
        selector:
          matchLabels:
            app: llama
        template:
          metadata:
            labels:
              app: llama
          spec:
            containers:
              - name: ollama
                image: ollama/ollama
                ports:
                - containerPort: 11434
              - name: ollama-init
                image: ollama/ollama
                command: [ "/bin/bash" ]
                args:
                  - -c
                  - |
                    set -ex
                    sleep 10
                    ollama run llama3.1
                    sleep infinity
    - apiVersion: v1
      kind: Service
      metadata:
        name: llama
      spec:
        type: ClusterIP
        ports:
          - port: 11434
            targetPort: 11434
        selector:
          app: llama
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: deepseek-r1
      spec:
        selector:
          matchLabels:
            app: deepseek-r1
        template:
          metadata:
            labels:
              app: deepseek-r1
          spec:
            containers:
              - name: ollama
                image: ollama/ollama
                ports:
                - containerPort: 11434
              - name: ollama-init
                image: ollama/ollama
                command: [ "/bin/bash" ]
                args:
                  - -c
                  - |
                    set -ex
                    sleep 10
                    ollama run deepseek-r1:8b
                    sleep infinity
    - apiVersion: v1
      kind: Service
      metadata:
        name: deepseek-r1
      spec:
        type: ClusterIP
        ports:
          - port: 11434
            targetPort: 11434
        selector:
          app: deepseek-r1
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vector-store
      spec:
        selector:
          matchLabels:
            app: vector-store
        template:
          metadata:
            labels:
              app: vector-store
          spec:
            containers:
              -   image: redis/redis-stack-server
                  name: workload
    - apiVersion: v1
      kind: Service
      metadata:
        name: vector-store
      spec:
        type: ClusterIP
        selector:
          app: vector-store
        ports:
          - port: 6379
            targetPort: 6379